name: build-pistomp-recovery

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/pistomp-recovery/**'
  pull_request:
    paths:
      - 'debpkgs/pistomp-recovery/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: pistomp-recovery
    secrets: inherit
