name: build-mod-midi-merger

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/mod-midi-merger/**'
  pull_request:
    paths:
      - 'debpkgs/mod-midi-merger/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: mod-midi-merger
    secrets: inherit
