name: build-browsepy

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/browsepy/**'
  pull_request:
    paths:
      - 'debpkgs/browsepy/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: browsepy
    secrets: inherit
