name: build-amidithru

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/amidithru/**'
  pull_request:
    paths:
      - 'debpkgs/amidithru/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: amidithru
    secrets: inherit
