name: build-sfizz-pistomp

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/sfizz-pistomp/**'
  pull_request:
    paths:
      - 'debpkgs/sfizz-pistomp/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: sfizz-pistomp
    secrets: inherit
