name: build-jack2-pistomp

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/jack2-pistomp/**'
  pull_request:
    paths:
      - 'debpkgs/jack2-pistomp/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: jack2-pistomp
    secrets: inherit
