name: build-jackbridge

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/jackbridge/**'
  pull_request:
    paths:
      - 'debpkgs/jackbridge/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: jackbridge
    secrets: inherit
