name: build-veja-1960-cab-lv2

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/veja-1960-cab-lv2/**'
      - 'config.sh'
  pull_request:
    paths:
      - 'debpkgs/veja-1960-cab-lv2/**'
      - 'config.sh'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: veja-1960-cab-lv2
    secrets: inherit
