name: build-fluidsynth-headless

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/fluidsynth-headless/**'
  pull_request:
    paths:
      - 'debpkgs/fluidsynth-headless/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: fluidsynth-headless
    secrets: inherit
