name: build-pi-stomp

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/pi-stomp/**'
  pull_request:
    paths:
      - 'debpkgs/pi-stomp/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: pi-stomp
    secrets: inherit
