name: build-mod-ui

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/mod-ui/**'
  pull_request:
    paths:
      - 'debpkgs/mod-ui/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: mod-ui
    secrets: inherit
