name: build-mod-ttymidi

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/mod-ttymidi/**'
  pull_request:
    paths:
      - 'debpkgs/mod-ttymidi/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: mod-ttymidi
    secrets: inherit
