name: build-mod-host-pistomp

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/mod-host-pistomp/**'
  pull_request:
    paths:
      - 'debpkgs/mod-host-pistomp/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: mod-host-pistomp
    secrets: inherit
