name: build-hylia

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/hylia/**'
  pull_request:
    paths:
      - 'debpkgs/hylia/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: hylia
    secrets: inherit
