name: build-pistomp-recovery

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/pi-stomp/**'
      - 'config.sh'
  pull_request:
    paths:
      - 'debpkgs/pi-stomp/**'
      - 'config.sh'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: pi-stomp
      custom_build_deps: lg 
    secrets: inherit
